export default {
  tabIconDefault: "#ccc",
  tabBar: "#fefefe",
  errorBackground: "red",
  errorText: "#fff",
  warningBackground: "#EAEB5E",
  warningText: "#666804",
  noticeText: "#fff",
  navyBlue: "#071526",
  oceanBlue: "#1B324F",
  primeRed: "#AB0A26",
  dullRed: "#7a091c",
  warmYellow: "#FFA626",
  white: "#fff",
  successGreen: "#35AC5E",
  grey: "#8c8c8c",
  lightGrey: "#d4d4d4",
  veryLightGrey: "#edf0ee",
};
