// ATTENDEE ACTIONS
const CHECKIN_ATTENDEE = 'CHECKIN_ATTENDEE';

// SIGNIN ACTIONS
const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export { CHECKIN_ATTENDEE, LOGIN_ATTEMPT, LOGIN_SUCCESS };
 