// ATTENDEE ACTIONS
const CHECKIN_ATTENDEE = 'CHECKIN_ATTENDEE';
const SET_CHECKOUT = 'SET_CHECKOUT';

// SIGNIN ACTIONS
const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export { CHECKIN_ATTENDEE, LOGIN_ATTEMPT, LOGIN_SUCCESS, SET_CHECKOUT };
 