// ATTENDEE ACTIONS
const CHECKIN_ATTENDEE = 'CHECKIN_ATTENDEE';
const SET_CHECKOUT = 'SET_CHECKOUT';
const SET_CHECKOUTMODAL = 'SET_CHECKOUTMODAL';

// SIGNIN ACTIONS
const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export { CHECKIN_ATTENDEE, LOGIN_ATTEMPT, LOGIN_SUCCESS, SET_CHECKOUT, SET_CHECKOUTMODAL };
 